spring.datasource.url=jdbc:mysql://localhost:3306/vetcommunity
spring.datasource.username=root
spring.datasource.password=root2004tot@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ???? ??????? ??? (?????? ???? ???? ?? ???? ???????)
frontend.url=http://localhost:5173

jwt.secret=MySuperSecretKeyForJWTThatIsVeryLongAndSecure1234567890
JWT_TOKEN=MySuperSecretKeyForJWTThatIsVeryLongAndSecure1234567890

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dn1xklmba}
cloudinary.api-key=${CLOUDINARY_API_KEY:759312276493669}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:Cey2Kx5Cod-pp6t9U2ft8HJQHGg}
spring.servlet.multipart.max-file-size=8MB
spring.servlet.multipart.max-request-size=32MB
