spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USER}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

jwt.secret=${JWT_TOKEN}

frontend.url=${FRONTEND_URL}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
spring.servlet.multipart.max-file-size=8MB
spring.servlet.multipart.max-request-size=32MB
