spring.profiles.active=dev

# ????? ??????? ???? ??????? ${ }
spring.datasource.url=jdbc:mysql://localhost:3306/vetcommunity?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root2004tot@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ??????? Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ???? ??????? ??? (?????? ???? ???? ?? ???? ???????)
frontend.url=http://localhost:5173

# ?? ????? ??? JWT
jwt.secret=MySuperSecretKeyForJWTThatIsVeryLongAndSecure1234567890
JWT_TOKEN=MySuperSecretKeyForJWTThatIsVeryLongAndSecure1234567890

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dn1xklmba}
cloudinary.api-key=${CLOUDINARY_API_KEY:759312276493669}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:Cey2Kx5Cod-pp6t9U2ft8HJQHGg}
spring.servlet.multipart.max-file-size=8MB
spring.servlet.multipart.max-request-size=9MB
